### ISSUE TITLE
snapshot-vms isn't finding vms

### ISSUE THREAD

**Issue by tallenaz** [sul-dlss/systeam-reporting#84]
For example:
```bash
$ ./snapshot-vms this-dev-env
Error: VM 'this-dev-vm' does not exist
```
Though I can see `this-dev-vm` in the farm. The call to `stack-servers` returns the correct hostname, so likely something about the `remctl` call gets us closer to the source of the problem. This error first showed up on Dec. 14 -- the week prior, was able to snapshot everything.

**Comment by jonrober** [comment]
The config file for ezmomi was updated to point to the new vmware server.  It can't take multiple servers to act against, so you'd need to pull an old copy of the config file and run directly on badwolf.

* Get the older version of the file /etc/ezmomi/config.yml from puppet and install it to /etc/ezmomi/config-old.yml on badwolf.
* Log onto badwolf and set EZMOMI_CONFIG to that location.
* On badwolf, for each server run the commands that snapshot-vms usually does via remctl:

ezmomi removeSnapshot --vm $hostname --name prekernel
ezmomi createSnapshot --vm $hostname --name prekernel

**Comment by tallenaz** [comment]
I think the config is correctly set up, but:

```
# EZMOMI_CONFIG=/etc/ezmomi/config-old.yml ezmomi removeSnapshot --vm esp-dev-jgreben --name prekernel
Traceback (most recent call last):
  File "/usr/bin/ezmomi", line 4, in <module>
    cli.cli()
  File "/usr/lib/python2.6/site-packages/ezmomi/cli.py", line 40, in cli
    ez.removeSnapshot()
  File "/usr/lib/python2.6/site-packages/ezmomi/ezmomi.py", line 408, in removeSnapshot
    self.config['name'])
  File "/usr/lib/python2.6/site-packages/ezmomi/ezmomi.py", line 365, in get_snapshot_by_name
    self.get_all_snapshots(vm) if
StopIteration
```

**Comment by tallenaz** [comment]
I had some success with one of the workarounds -- just creating a new snapshot with `createSnapshot`. But, that command requires `vm` and `name` flags, and I can't get the `name` for every machine I want to snapshot with `listSnapshot`:
 ```bash
# trying to list workflow-stage snapshots w/ any config
[root@badwolf azanella]# EZMOMI_CONFIG=/etc/ezmomi/config-old.yml ezmomi listSnapshots --vm workflow-stage
No snapshots for workflow-stage
[root@badwolf azanella]# EZMOMI_CONFIG=/etc/ezmomi/config.yml ezmomi listSnapshots --vm workflow-stage
Error: VM 'workflow-stage' does not exist

# getting and creating a snapshot for dev
[root@badwolf azanella]# EZMOMI_CONFIG=/etc/ezmomi/config-old.yml ezmomi listSnapshots --vm workflow-dev
VM                              Snapshot        Create Time                        
'vim.VirtualMachine:vm-2974'    workflow-dev    2016-10-28 12:21:36.623951+00:00   
[root@badwolf azanella]# EZMOMI_CONFIG=/etc/ezmomi/config-old.yml ezmomi createSnapshot --vm workflow-dev --name 'vim.VirtualMachine:vm-2974'
Created snapshot for workflow-dev

# can't create for stage w/o the name listSnapshots would return
[root@badwolf azanella]# EZMOMI_CONFIG=/etc/ezmomi/config-old.yml ezmomi createSnapshot --vm workflow-stage
usage: ezmomi createSnapshot [-h] --vm VM --name NAME [--memory] [--quiesce]
ezmomi createSnapshot: error: argument --name is required
```

**Comment by jonrober** [comment]
--name should be the snapshot name, so in this case prekernel.  The listSnapshots command isn't helping right there, since it's listing the VM id rather than name, and the snapshot name in that case happens to be the VM name just by chance, because that snapshot was created during early testing way back when I hadn't thought through the convention well enough. 

Currently working at the code, just dumped the snapshot object it's printing and verified that it's a linked list and the current ezmomi code isn't treating it as such, thus the base problem.

**Comment by jonrober** [comment]
Okay, ugh.  I'm going to pause on the work here because I think it opens something more general about how we want to handle snapshotting and removing snapshots, for the general group to discuss, maybe at next ops meeting.

I've added (but not pushed out) a change so that the list command can walk the tree instead of just showing the root snapshot.  That'll also need to go to deleting.  However, a delete command can take 12m when it's actually working correctly (which it hadn't been before because of this problem).  That's not something we want to be doing on the fly as part of our normal process, since running it on the CLI won't just fire and forget the process.  So doing ten machines takes over an hour and a half running serially and ugh, nope, that won't scale at all.

So before I do more work on changing ezmomi, I'd like us to sit down and figure out how to actually automate at least the cleaning part of the process.  Maybe hitting the vmomi library directly to delete every snapshot older than 14/30/90 days, as a single automated process that can take as long as it wants?

**Comment by tallenaz** [comment]
@jonrober any progress on this issue?

**Comment by jonrober** [comment]
Sorry, I think we had the next meeting cancelled or full of other stuff, and then with a week plus to wait it slipped from my mind.  I think.  Or do you recall us talking about it?  I'm going very fuzzy on what happened there.

@julianmorley - could you add a topic for next meeting to talk about snapshots, unless one of you recalls that we already did?

**Comment by tallenaz** [comment]
I'm fuzzy on details too, it's been a while since I've been to a systeam meeting.

**Comment by jonrober** [comment]
Just a heads-up, I'm going to just write this up in summary and get responses on slack, since we're having bad luck with meets. :)
